### PR TITLE
Fix up Git ignores. Fixes build errors.

### PR DESCRIPTION
**Pull request by mtwilliams**
Woops. Didn't notice that a rule in the `.gitignore` was causing much needed code to be excluded.

### CODE REVIEW

**Comment by paulodiniz** [comment]
@mtwilliams Cool! Can you just merge master and we are good to go

**Comment by mtwilliams** [comment]
@paulodiniz :rocket:

**Comment by mtwilliams** [comment]
@paulodiniz you'll have to revert the revert...

**Comment by mtwilliams** [comment]
I'll go ahead and rebase to build a fully working self-contained commit.

**Comment by paulodiniz** [comment]
@mtwilliams If I revert the revert it won't have the modules that were missing (tried to do that now). Can you send another PR and I will accept it right away

**Comment by mtwilliams** [comment]
Voilà @paulodiniz

**Comment by paulodiniz** [comment]
:+1: thanks!

**Comment by mtwilliams** [comment]
Note that this does break backwards compatibility, nothing you can't resolve with a find-and-replace `Xe.fetch` => `Xe.rates!` :)

**Pull request merged**
